### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /usr/bin/winemaker --lower-uppercase --nomfc --dll . -irt -lrt


SRCDIR                = .
SUBDIRS               =
DLLS                  = shmbridge.dll
LIBS                  =
EXES                  =



### Common settings

CEXTRA                = -mno-cygwin -std=gnu17
CXXEXTRA              =
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          =
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             = -lrt


### shmbridge.dll sources and settings

shmbridge_dll_MODULE  = shmbridge.dll
shmbridge_dll_C_SRCS  = shmbridge.c
shmbridge_dll_CXX_SRCS=
shmbridge_dll_RC_SRCS =
shmbridge_dll_LDFLAGS = -shared \
			$(shmbridge_dll_MODULE:.dll=.spec) \
			-mno-cygwin
shmbridge_dll_ARFLAGS =
shmbridge_dll_DLL_PATH=
shmbridge_dll_DLLS    = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
shmbridge_dll_LIBRARY_PATH=
shmbridge_dll_LIBRARIES= uuid

shmbridge_dll_OBJS    = $(shmbridge_dll_C_SRCS:.c=.o) \
			$(shmbridge_dll_CXX_SRCS:.cpp=.o) \
			$(shmbridge_dll_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(shmbridge_dll_C_SRCS)
CXX_SRCS              = $(shmbridge_dll_CXX_SRCS)
RC_SRCS               = $(shmbridge_dll_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(shmbridge_dll_MODULE).so: $(shmbridge_dll_OBJS) $(shmbridge_dll_MODULE:.dll=.spec)
	$(CC) $(shmbridge_dll_LDFLAGS) -o $@ $(shmbridge_dll_OBJS) $(shmbridge_dll_LIBRARY_PATH) $(shmbridge_dll_DLL_PATH) $(DEFLIB) $(shmbridge_dll_DLLS:%=-l%) $(shmbridge_dll_LIBRARIES:%=-l%)


