name: Build project

on:
  push:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt install --install-recommends winehq-stable wine-devel wine-devel-dev wine-devel-i386 mingw-w64-common mingw-w64-i686-dev mingw-w64-x86-64-dev mingw-w64 mingw-w64

      - name: Build project
        run: |
          bash Build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-shmbridge
          path: '*.so'
