name: Build project

on:
  push:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wine and winecc
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32 wine64-tools libwine-dev libwine mingw-w64

      - name: Build project
        run: |
          bash Build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-shmbridge
          path: '*.so'
