name: Build project

on:
  push:

jobs:
  build-project:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wine and winecc
        run: |
          sudo dnf install -y wine wine-devel @development-tools

      - name: Build project
        run: |
          bash Build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-shmbridge
          path: '*.so'
